name: Schedule Run

on:
  schedule:
    - cron: '0 0/8 * * *'

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install socket
          pip install datetime

      - name: Run script
        run: python run.py

  manual_run:
    runs-on: ubuntu-latest
    needs: run_python
    steps:
      - name: Manual Run
        run: echo "This is a manual run"
